let suggestions = [
    "Badminton",
    "Tennis",
    "Sport",
    "Adidas",
    "Nike",
    "Nike Air Force 1 Low Retro",
    "Nike Air Force 1'07",
    "Nike Blaze Mid 77 Vintage",
    "Premium Gold Nike",
    "Sneakers Dragon",
    "Super Blue",
    "Street Shoez",
    "Gladiator Shoes",
    "Jordan Blamez",
    "Zooja",
    "Vans",
    "Leather Sneaker",
    "Sock",
    "Branchs",
    "Men",
    "Women",
    "Trendy",
    "Adidas Super Star",
    "Adidas Stan Smith",
    "NMD_R1 PrimeBlue",
    "Jordan 1",
    "Jordan 2",
    "Jordan 3",
    "Jordan limmited",
    "Limited"
];
